---
fixtures:
  repositories:
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt
      tag: v10.0.1
    chocolatey: https://github.com/puppetlabs/puppetlabs-chocolatey
    concat: https://github.com/puppetlabs/puppetlabs-concat
    icinga: https://github.com/voxpupuli/puppet-icinga
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo
