name 'puppet-icinga2'
version '0.4'
source 'git://github.com/nickchappell/puppet-icinga2.git'
author 'Nick Chappell'
license 'Apache 2.0'
summary 'Icinga 2 Puppet module'
description 'A module for installing and configuring the Icinga 2 monitoring system'
project_page 'https://github.com/nickchappell/puppet-icinga2'
dependency 'puppetlabs/apt', '>= 1.5.0'