forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib', :latest
mod 'puppetlabs/concat', :latest
mod 'puppetlabs/apt', '1.8.0'
mod 'icinga2',
  :git    => 'git@git.icinga.org:puppet-icinga2-rewrite.git',
  :branch => 'master'
