forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'icinga2',
  :git    => 'git@git.icinga.org:puppet-icinga2-rewrite.git',
  :branch => 'master'
