# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = {
  'i2sles12sp1puppet4' => {
    :box => 'sles-12-sp1-x64-virtualbox.box',
    :url => 'http://boxes.icinga.com/vagrant/sles/sles-12-sp1-x64-virtualbox.box',
    :md5 => 'f69a32869d2cffc240e95e9089d3e63a'
  },
  'i2rhel7puppet4' => {
    :box => 'centos-7.2-x64-virtualbox',
    :url => 'http://boxes.icinga.org/vagrant/centos/centos-7.2-x64-virtualbox.box',
    :md5 => '30fe8faeaf5e67d1dfcdeb8631e757e7'
  },
  'i2rhel6puppet4' => {
    :box => 'centos-6.7-x64-virtualbox',
    :url => 'http://boxes.icinga.org/vagrant/centos/centos-6.7-x64-virtualbox.box',
    :md5 => 'ef0c3e7a9d798a911a908c77dd816e94'
  },
  'i2debian8puppet4' => {
    :box => 'debian-8.5-amd64-virtualbox',
    :url => 'http://boxes.icinga.org/vagrant/debian/debian-8.5-amd64-virtualbox.box',
    :md5 => '4562c14ba044a2a163836bfec3767e63'
  },
  'i2debian7puppet4' => {
    :box => 'debian-7.11-amd64-virtualbox',
    :url => 'http://boxes.icinga.org/vagrant/debian/debian-7.4-amd64.box',
    :md5 => '78dc5710545789da74f5b3727a20e453'
  },
  'i2ubuntu14puppet4' => {
    :box => 'ubuntu-14.04.4-x64-virtualbox',
    :url => 'http://boxes.icinga.org/vagrant/ubuntu/ubuntu-14.04.4-x64-virtualbox.box',
    :md5 => '2280f5471cb63cc1c01e78880185fe02'
  },
  'i2ubuntu16puppet4' => {
    :box => 'ubuntu-16.04-amd64-virtualbox.box',
    :url => 'http://boxes.icinga.org/vagrant/ubuntu/ubuntu-16.04-amd64-virtualbox.box',
    :md5 => '9e0b3ff7ad4c4b5782110c1784c9a051'
  },
  'i2w2k12r2puppet4' => {
    :box => 'w2k12r2-x64-virtualbox',
    :url => 'http://boxes.icinga.org/vagrant/private/w2k12r2.box',
    :md5 => '8d2f63885253289bfcad47256146ea02'
  },
}

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  nodes.each_pair do |name, options|
    config.vm.define name do |node_config|
      node_config.vm.box = options[:box]
      node_config.vm.hostname = "#{name}"
      node_config.vm.box_url = options[:url]
      node_config.vm.box_download_checksum = options[:md5]
      node_config.vm.box_download_checksum_type = 'md5'
      node_config.vm.network :private_network, :adapter => 2, ip: options[:ip] if options[:ip]

      if options[:forwarded]
        options[:forwarded].each_pair do |guest, local|
          node_config.vm.network "forwarded_port", guest: guest, host: local
        end
      end

      node_config.vm.provider :virtualbox do |vb|
        vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
        vb.name = name
        vb.gui = false
        vb.customize ["modifyvm", :id,
          "--groups", "/icinga2",
          "--memory", "512",
          "--audio", "none",
          "--usb", "on",
          "--usbehci", "off",
          "--nic2", "intnet",
        ]
        vb.memory = options[:memory] if options[:memory]
        vb.cpus = options[:cpus] if options[:cpus]
      end

      node_config.vm.provision :shell,
        :path => "scripts/#{name}.sh" if options[:box] != "w2k12r2-x64-virtualbox"
      node_config.vm.provision :shell,
        :path => "scripts/#{name}.bat" if options[:box] == "w2k12r2-x64-virtualbox"

      node_config.vm.provision :puppet do |puppet|
        puppet.environment = "production"
        puppet.environment_path = "environments"
        puppet.hiera_config_path = "hiera.yaml"
      end

    end
  end

end
