# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = {
  'i2rhel7puppet4' => {
    :box => 'centos-7.2-x64-virtualbox',
    :url => 'http://boxes.netways.org/vagrant/centos/centos-7.2-x64-virtualbox.box',
    :md5 => '30fe8faeaf5e67d1dfcdeb8631e757e7'
  },
  'i2rhel6puppet4' => {
    :box => 'centos-6.7-x64-virtualbox',
    :url => 'http://boxes.netways.org/vagrant/centos/centos-6.7-x64-virtualbox.box',
    :md5 => 'ef0c3e7a9d798a911a908c77dd816e94'
  },
}

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  nodes.each_pair do |name, options|
    config.vm.define name do |node_config|
      node_config.vm.box = options[:box]
      node_config.vm.hostname = "#{name}.localdomain"
      node_config.vm.box_url = options[:url]
      node_config.vm.box_download_checksum = :md5
      node_config.vm.box_download_checksum_type = 'md5'
      node_config.vm.network :private_network, :adapter => 2, ip: options[:ip] if options[:ip]

      if options[:forwarded]
        options[:forwarded].each_pair do |guest, local|
          node_config.vm.network "forwarded_port", guest: guest, host: local
        end
      end

      node_config.vm.provider :virtualbox do |vb|
        vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
        vb.name = name
        vb.gui = false
        vb.customize ["modifyvm", :id,
          "--groups", "/icinga2",
          "--memory", "512",
          "--audio", "none",
          "--usb", "on",
          "--usbehci", "off",
          "--nic2", "intnet",
        ]
        vb.memory = options[:memory] if options[:memory]
        vb.cpus = options[:cpus] if options[:cpus]
      end

      node_config.vm.provision :shell,
        :path => "scripts/#{name}.sh"

      node_config.vm.provision :puppet do |puppet|
        puppet.environment = "production"
        puppet.environment_path = "environments"
        puppet.hiera_config_path = "hiera.yaml"
      end

    end
  end

end
